### PR TITLE
type conversion for view limit params

### PR DESCRIPTION
**Pull request by jchris**
This fixes https://github.com/couchbase/sync_gateway/issues/1188 but brings up the fact that our tests for this are not in this repo.

### CODE REVIEW

**Comment by adamcfraser** [comment]
Am I right in thinking that ProcessViewResult is only ever used for Walrus results?  Does it make sense to move it there (and move the test for it there), or would that refactoring have the potential to break things elsewhere?

**Comment by jchris** [comment]
I don't really know what the type hierarchy looks like. My gut says you are
right, but maybe ask Traun.

**Comment by jchris** [comment]
Tag @tleyden maybe you can write out a quick summary of how the sg-bucket, walrus, bucket interface / inheritance hierarchy works. I understand it's in the middle of a refactoring, so I just want to make sure I'm refactoring in the right direction.

**Comment by jchris** [comment]
Discussed and found the origin of the uint64 type https://github.com/couchbase/sync_gateway/blob/master/src/github.com/couchbase/sync_gateway/rest/handler.go#L282

**Comment by jchris** [comment]
For the record, the way it's structured is sg-bucket contains functionality and interface definitions shared by Walrus and ForestDB.

Now I’m wondering how sg-bucket, db.Bucket, and CouchbaseBucket are related, and how that interacts with switching eg from go-couchbase to gocb.

**Comment by adamcfraser** [comment]
sg-bucket has two roles:
1. Abstracts the bucket interface used by Sync Gateway.  Walrus, CouchbaseBucket (a go-couchbase backed bucket), and the upcoming CouchbaseBucketGoCB all need to implement that interface in order to be used by SG.
2. Contains a set of utility methods/functionality that may be utilized by any of those bucket implementations.

**Comment by jchris** [comment]
One benefit I can see to splitting out something like `sg-bucket-interface` and `sg-bucket-utils` modules is that you'd be able to tell at a glance when reading code if you are looking at something that's implemented once in the sg-bucket-utils module, or multiple times in the various implementations of the sg-bucket-interface.

Or maybe I'm wrong and there are other easy ways to tell what you are looking at in the source base.

**Pull request merged**
