### PR TITLE
Feature/revert master

### PR DESCRIPTION
**Pull request by jchris**
I think this should be not all of these commits. Which ones @adamcfraser and @tleyden ?

### CODE REVIEW

**Comment by adamcfraser** [comment]
I feel like we could make the changes on sync-gateway/master to uptake these changes on sg-bucket with very little work, and very little risk (at most I think it would be implementing stubs in things like leakybucket and loggingbucket).  I don't mind putting together a quick PR for that on sync-gateway/master.

**Comment by tleyden** [comment]
@adamcfraser - agreed

**Comment by adamcfraser** [comment]
Created a PR on sync-gateway/master to support the latest sg-bucket:
https://github.com/couchbase/sync_gateway/pull/1131

**Comment by jchris** [comment]
no longer needed

**Pull request closed without merging**
